### ISSUE TITLE
Is it possible that you can intergrate all features into one file

### ISSUE THREAD

**Issue by jxnx888** [joe223/tiny-swiper#10]
**Is it possible that you can intergrate all features into one file**
Hi Joe,
I can load specific plugin in my project, but can we just load one file?
I tried to put the plugins into one file, but it did not work. 
Thanks!

**Comment by joe223** [comment]
> I tried to put the plugins into one file, but it did not work.
@jxnx888 Would you mind provide a repo for reproducing this problem?

**Comment by jxnx888** [comment]
sure

**Comment by joe223** [comment]
@jxnx888 😂 I mean, show me a repository which reproduce the issue that you can't put plugins into one file.
