### ISSUE TITLE
Unable to subscribe to `before-init` and `after-init` hooks

### ISSUE THREAD

**Issue by stigi** [joe223/tiny-swiper#23]
**Describe the bug**

One can only subscribe to events when the object is already initialized, and at that point the constructor is done and the events were emitted already. This means they are pretty useless.

**Expected behavior**
Maybe it makes sense to pass the event as kind of _callbacks_ in the config

**Information**
 - Tiny-Swiper Version: 1.3.0
 - OS: all of them
 - Browser: all of them

**Comment by joe223** [comment]
> One can only subscribe to events when the object is already initialized, and at that point the constructor is done and the events were emitted already. This means they are pretty useless.

`before-init` and `after-init` was used in plugins frequently. But does not have a major effect for users.

- `before-init` emitted on Swiper instance is created, *but* dose not initialize layout ,listener and so on at that time.
- `after-init` emitted while everything is settled.

Example, we have to inject some custom configuration before instance initialized or change some internal configuration before DOM rendered prevent repaint/reflow happening.

We can get the initialization flow with this code (v1.3.0):

```javascript
constructor (el, config) {
        config = Swiper.formatConfig(config)
        el = typeof el === 'string' ? document.body.querySelector(el) : el

        this.index = 0
        this.scrolling = false
        this.config = config
        this.supportTouch = detectTouch()
        this.$el = el
        this.$wrapper = el.querySelector(`.${config.wrapperClass}`)
        this.eventHub = {}
        this.initPlugins(config.plugins || Swiper.plugins)
        this.emit('before-init', this)
        this.initListener()
        this.initTouchStatus()
        this.initWheelStatus()
        this.update()
        this.attachListener()
        this.emit('after-init', this)
        this.scroll(config.initialSlide)
}
```

**Comment by stigi** [comment]
Oh I see, Plugins get initialized before the constructor finishes, so they can hook into those events. Makes sense. Thanks for pointing this out 🙏 

Some context on my question. We have a use case where we initialize Swiper with an `initialSlide` bigger than 0 and this caused an initial animation on first render. Buy workaround was to set `speed` to 0 when constructing Swiper, and then set it back to 300 and calling `update()` afterwards. I tried doing this using `before-init` and `after-init` in an earlier attempt.

**Comment by stigi** [comment]
(I'll close the issue since since https://github.com/joe223/tiny-swiper/issues/23#issuecomment-699845097 gives a good explanation. Might be worth considering adding the special nature of those hooks to the documentation though).
