### ISSUE TITLE
Pagination bullet issue with slidesPerView

### ISSUE THREAD

**Issue by mittermayr** [joe223/tiny-swiper#27]
**Describe the bug**
Having 4 slides, setting `slidersPerView=2` and using the pagination plugin leads to 4 bullet points (pagination dots) instead of 2. Moreover, with 2 slides per view displayed, there is no content to scroll to on the right but it still shows two dots indicating that there is. 

**Expected behavior**
Dots should represent screens I can swipe to, instead of the individual elements (or slides). Having only 2 slides but displaying all two on the same screen (for example, in a landscape view, vs. switching back to`slidersPerView=1` on portrait) means that there's two bullet indicators (first selected, second lighter gray), but I can't scroll right (of course, because there's no more content).

**Information**
 - Tiny-Swiper Version: latest version
 - OS: iOS/Chrome
 - Browser: Chrome

I took a quick look at the code to see if I can submit a PR, but it's not that straight forward since you're basing the dots off the page list, which is the list of slides. I feel like that entire part would need to be rewritten somewhat to calculate the dots based along something like `total_dots = Math.ceil(total_slides / slidesPerView)` (but smarter). Not sure how the partial values in `slidesPerView` would interfere here. 

![landscape](https://user-images.githubusercontent.com/999171/97430123-b3b7aa80-1918-11eb-882f-65174e3400a1.gif)

**Comment by joe223** [comment]
With the curtly review, I thought we can get `total_dot` value through 

```
total_dots = total_slides - Math.ceil(slidesPerView) + 1
```

PR always welcomed

**Comment by joe223** [comment]
https://github.com/joe223/tiny-swiper/pull/28

**Comment by mittermayr** [comment]
Beautifully fixed, I just rolled it out and it works a treat. I have a deadline this evening for a hefty website that uses the swiper and I had planned to spend the afternoon trying to figure out a temporary fix — so your update here comes as a fantastic weekend surprise. Thanks again, top work.

**Comment by joe223** [comment]
@mittermayr I'm glad to hear that. It's also my pleasure. Have a nice weekend !
