### ISSUE TITLE
SwiperPluginKeyboardControl exported incorrectly

### ISSUE THREAD

**Issue by pablomercadolibre** [joe223/tiny-swiper#36]
**Describe the bug** 
esm version is exporting the incorrect module for SwiperPluginKeyboardControl, you can check [index.esm.js](https://github.com/joe223/tiny-swiper/blob/master/src/index.esm.js#L5)
I've attached a demo for the issue but i think is self-explanatory, i can create a PR if you want, also i'd like yo ask you about v2, have you released any alpha/beta package with v2 so we can give it a try ?

Thanks!!!

**Expected behavior**
Export SwiperPluginKeyboardControl with the expected module

**Information**
 - Tiny-Swiper Version: v1.3.2
 - OS: All
 - Browser: All
 - Reproduce example：[https://codesandbox.io/s/suspicious-cloud-scfzs](https://codesandbox.io/s/suspicious-cloud-scfzs)

**Comment by joe223** [comment]
Oh, what a silly mistake! 🙁

@pablomercadolibre I'll be wild glad if you create the fix PR!

Version `2.0.0-alpha.0` is plan to be released this weekend.

**Comment by pablomercadolibre** [comment]
Great, i've just created the PR and looking forward for v2, thanks!
