### ISSUE TITLE
Scrolling on .swiper-slide fires "before-slide" and "after-slide" hooks.

### ISSUE THREAD

**Issue by narasab** [joe223/tiny-swiper#49]
**Describe the bug**
In a horizontal swiper (.swiper-slide) scrolling on a slide vertically fires before-slide and after-slide hooks.

**Expected behavior**
Vertical scrolling should not fire slide events in a horizontal swiper.

**Information**
 - Tiny-Swiper Version: 2.0.0-alpha.6

**Comment by joe223** [comment]
https://github.com/joe223/tiny-swiper/issues/46#issuecomment-753165787
