### ISSUE TITLE
Navigation plugin not in index.full.js

### ISSUE THREAD

**Issue by eddneal** [joe223/tiny-swiper#50]
Hi I noticed that this is missing, is it intentional?

Great swiper btw, thanks a lot.

**Comment by joe223** [comment]
Thanks for the feedback @eddneal 

index.full.js maybe deprecated. There are some potential conflicts if loading multiple plugins. For example, there will occur error if two plugins each of them provides different slide effect. So `full.js` may not be really full-featured.

Would you like to make a PR to add navigation to `index.full.js`? 😁

**Comment by joe223** [comment]
Fixed 3d77ec7c10f0b5681fc9c2637d7d9afb79e820d3

**Comment by eddneal** [comment]
Thank you! This is greatly appreciated.
