### ISSUE TITLE
“[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false”

### ISSUE THREAD

**Issue by narasab** [joe223/tiny-swiper#53]
**Describe the bug**
When swiping in android webview this error is thrown.
“[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false”

**Information**
 - Tiny-Swiper Version: v2.0.0
 - OS: Android
 - Browser: Android System WebView (Chrome 87)

**Comment by joe223** [comment]
Ref: https://github.com/joe223/tiny-swiper/pull/54
