### ISSUE TITLE
Make Swiper resizable

### ISSUE THREAD

**Issue by harshmandan** [joe223/tiny-swiper#67]
**Describe the bug**
The swiper is not very responsive. I'm making use of this library in my project where the windows can be resized.
Here's' the bug in video format: 
https://streamable.com/40xqoa

**Expected behavior**
It should be responsive.

**Comment by joe223** [comment]
Hi @harshmandan , Here is a demo may be useful https://github.com/joe223/tiny-swiper/blob/dev/packages/tiny-swiper/demo/resize.html

Would you like to create a Resize plugin ? It should be placed in this directory https://github.com/joe223/tiny-swiper/tree/dev/packages/tiny-swiper/src/modules

**Comment by harshmandan** [comment]
@joe223 Thanks for the example.
This worked nicely:
```js
window.addEventListener('resize', () => mySwiper.updateSize())
```

I'll try to create to module as soon as I get the time. Thanks

**Comment by joe223** [comment]
Try to add a debounce function to the window resize listener for better performance

pseudocode

```JavaScript
window.addEventListener('resize', _.debounce(() => mySwiper.updateSize(), 400))
```

@harshmandan
