### ISSUE TITLE
Element is generating max index having into account shallow slides

### ISSUE THREAD

**Issue by josemrodrigu** [joe223/tiny-swiper#74]
**Describe the bug**
Having a "infinite" swiper (**loop** mode on) and **resize** enabled, there is an issue on the instance update. 
Suddenly, the max index of the instance changes, because Element is taking into account slides with the data-shallow-slider attribute.

**Expected behavior**
The max index of the instance should not be affecteddue to a resize.

**Information**
 - Tiny-Swiper Version: v2.1.2
 - OS: MACos 10.15.7, windows 8, windows 10.
 - Browser: Chrome 96
 - Reproduce example：[e.g. https://codier.io/creation/BJzZFIJ6t]

**Comment by joe223** [comment]
https://github.com/joe223/tiny-swiper/pull/75

**Comment by josemrodrigu** [comment]
@joe223 do you have an expected publication date for this issue?

Thanks!

**Comment by josemrodrigu** [comment]
@joe223

**Comment by joe223** [comment]
@josemrodrigu  Sorry for the late reply. 

`2.2.0` was released. 

API: https://tiny-swiper.js.org/docs/api#breakpoints. Demo: https://tiny-swiper.js.org/docs/demo#breakpoints

**Comment by josemrodrigu** [comment]
thanks Joe!
