### ISSUE TITLE
Regarding the lazy load

### ISSUE THREAD

**Issue by jxnx888** [joe223/tiny-swiper#9]
**In your project, i did not find the lazy load part, do you have one with lazyload?.**
The lazyload is a very important and useful part, you might have it. [...]

**Comment by joe223** [comment]
Do you mean a feature which same with https://swiperjs.com/api/#lazy?

**Comment by joe223** [comment]
@jxnx888 https://github.com/joe223/tiny-swiper#lazyload

**Comment by jxnx888** [comment]
Thanks dude!
